name: traffic4cast
channels:
  - pytorch
  - defaults
dependencies:
    - python=3.6
    - pytorch::pytorch>=1.0
    - pytorch::torchvision
    - pytorch::ignite
    - cudatoolkit=10.0
    - numpy
    - h5py
    - matplotlib
    - tabulate
    - plotly
    - hpbandster
