name: traffic4cast
dependencies:
    - python=3.6
    - pytorch>=1.0::pytorch
    - torchvision::pytorch
    - cudatoolkit=9.0::pytorch
    - ignite::pytorch
    - numpy
    - h5py
    - matplotlib
    - tabulate
